parameters:
    lychee_admin.service.manager.class: Lychee\Bundle\AdminBundle\Service\ManagerService
    lychee_admin.service.role.class: Lychee\Bundle\AdminBundle\Service\RoleService
    lychee_admin.service.operation_accounts.class: Lychee\Bundle\AdminBundle\Service\OperationAccountsService
    lychee_admin.service.manager_log.class: Lychee\Bundle\AdminBundle\Service\ManagerLog\ManagerLogService


services:
#    lychee_admin.example:
#        class: %lychee_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lychee_admin.service.manager:
        class: %lychee_admin.service.manager.class%
        arguments: [@security.encoder_factory, @doctrine, ~]

    lychee_admin.service.role:
        class: %lychee_admin.service.role.class%
        arguments: [@doctrine, ~]

#    kernel.listener.authorization:
#        class: Lychee\Bundle\AdminBundle\EventListener\AuthorizationListener
#        arguments:
#            - @service_container
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    lychee_admin.service.operation_accounts:
        class: %lychee_admin.service.operation_accounts.class%
        arguments: [@doctrine]

    lychee_admin.service.manager_log:
        class: %lychee_admin.service.manager_log.class%
        arguments: [@doctrine.orm.entity_manager]

    lychee_admin.service.favor:
        class: Lychee\Bundle\AdminBundle\Service\FavorService
        arguments:
            - @doctrine
            - ~

    lychee_admin.service.tag:
        class: Lychee\Bundle\AdminBundle\Service\TagService
        arguments:
            - @doctrine
            - ~

    lychee.twig_admin_extension:
        class: Lychee\Bundle\AdminBundle\Twig\Extension
        public: false
        tags:
            - { name: twig.extension }

    lychee_admin.event_dispatcher:
        class: Lychee\Bundle\AdminBundle\EventListener\EventDispatcher
        arguments: [@event_dispatcher]

    lychee_admin.event_subscriber:
        class: Lychee\Bundle\AdminBundle\EventListener\EventSubscriber
        arguments:
            - @lychee_admin.service.manager_log
            - @lychee_admin.service.graylist
        tags:
            - {name: kernel.event_subscriber}

    lychee_admin.service.graylist:
        class: Lychee\Bundle\AdminBundle\Service\GrayListService
        arguments:
            - @doctrine
            - @lychee.module.post

    lychee_admin.service.customize_content:
        class: Lychee\Bundle\AdminBundle\Service\CustomizeContentService
        arguments:
            - @doctrine