version: "3"

services: 

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - /docker/www/html:/usr/share/nginx/html:rw
      - /docker/www:/usr/share/nginx/html:rw
      - /docker/nginx:/etc/nginx/conf.d/:ro
      - /docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /docker/log/nginx/:/var/log/nginx/:rw
    links:
      - php-fpm:php-fpm
    privileged: true
    environment: 
      - TZ=Asia/Shanghai

  php-fpm:
    build: ./php/
    # image: php:fpm
    container_name: php-fpm
    expose:
      - "9000"
    volumes:
      # - /docker/www/html/:/usr/share/nginx/html:rw
      - /docker/www/:/usr/share/nginx/html:rw
      - /docer/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - /docker/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - /docker/log/php-fpm/:/var/log/php-fpm/:rw
    links:
      - mysql:mysql
      - redis:redis
    environment: 
      - TZ=Asia/Shanghai
    privileged: true

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /docker/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - /docker/mysql/:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    privileged: true 

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"