doctrine:
    dbal:
        default_connection: core
        connections:
            core:
                driver:   "%core_database_driver%"
                host:     "%core_database_host%"
                port:     "%core_database_port%"
                dbname:   "%core_database_name%"
                user:     "%core_database_user%"
                password: "%core_database_password%"
                charset:  UTF8MB4
                default_table_options:
                    charset:  utf8mb4
                    collate:  utf8mb4_general_ci
                    engine:   InnoDB
            weibo_robot:
                driver:   "%core_database_driver%"
                host:     "%core_database_host%"
                port:     "%core_database_port%"
                dbname:   "ciyo_robot"
                user:     "%core_database_user%"
                password: "%core_database_password%"
                charset:  UTF8MB4
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: core
        entity_managers:
            core:
                connection: core
                auto_mapping: true
