lsw_memcache:
    pools:
        default:
            servers:
                - { host: "%core_memcache_host%", tcp_port: "%core_memcache_port%" }
            options:
                allow_failover: true
                max_failover_attempts: 20
                default_port: 11211
                chunk_size: 32768
                protocol: ascii
                hash_strategy: consistent
                hash_function: crc32
                redundancy: true
                session_redundancy: 2
                compress_threshold: 20000
                lock_timeout: 15
    doctrine:
        metadata_cache:
            pool: default
            entity_manager: core          # the name of your entity_manager connection
            document_manager: core        # the name of your document_manager connection