snc_redis:
    clients:
#        default:
#            type: predis
#            alias: default
#            dsn: "redis://%redis_host%/0"
#            logging: "%kernel.debug%"
#            options:
#                connection_timeout: 5
#                connection_persistent: true
#                read_write_timeout: 5
#                iterable_multibulk: false
#                throw_errors: true
#        test:
#            type: predis
#            alias: test
#            dsn: "redis://127.0.0.1:6379/0"
#            options:
#                profile: 2.8
#                read_write_timeout: 10

        idgen:
            type: predis
            alias: idgen
            dsn: "redis://%core_redis_cache_host%:%core_redis_cache_port%/0"
            options:
                profile: 2.8
                read_write_timeout: 10
        cache:
            type: predis
            alias: cache
            dsn: "redis://%core_redis_cache_host%:%core_redis_cache_port%/0"
            options:
                profile: 2.8
                read_write_timeout: 3
        spam:
            type: predis
            alias: spam
            dsn: "redis://%core_redis_cache_host%:%core_redis_cache_port%/1"
            options:
                profile: 2.8
                read_write_timeout: 3
        recommendation_cache:
            type: predis
            alias: recommendation_cache
            dsn: "redis://%core_redis_cache_host%:%core_redis_cache_port%/2"
            options:
                profile: 2.8
                read_write_timeout: 3
        robot:
            type: predis
            alias: robot
            dsn: "redis://%core_redis_cache_host%:%core_redis_cache_port%/3"
            options:
                profile: 2.8
                read_write_timeout: 3

        recommendation:
            type: predis
            alias: recommendation
            dsn: "redis://%core_redis_db_host%:%core_redis_db_port%/1"
            options:
                profile: 2.8
                read_write_timeout: 10
        topic_visitor:
            type: predis
            alias: topic_visitor
            dsn: "redis://%core_redis_db_host%:%core_redis_db_port%/2"
            options:
                profile: 2.8
                read_write_timeout: 3
        recommendation_video:
            type: predis
            alias: recommendation_video
            dsn: "redis://%core_redis_db_host%:%core_redis_db_port%/3"
            options:
                profile: 2.8
                read_write_timeout: 3