services:
    lychee.module.content_management:
        class: Lychee\Module\ContentManagement\ContentManagementService
        arguments:
            - '@doctrine'
            - ~
            - '@memcache.default'
    lychee.module.input_domain_recorder:
        class: Lychee\Module\ContentManagement\InputDomainRecorder
        arguments:
            - '@doctrine'
    lychee.task.input_domain_daily_record:
        class: Lychee\Module\ContentManagement\Task\InputDomainDailyRecorderTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}
    lychee.module.content_management.domain_whitelist:
        class: Lychee\Module\ContentManagement\Domain\WhiteList
        arguments:
            - '@doctrine'
            - ~
    lychee.module.content_management.sticker:
        class: Lychee\Module\ContentManagement\StickerManagement
        arguments:
            - '@doctrine'
            - ~
    lychee.module.content_management.search_keyword:
        class: Lychee\Module\ContentManagement\SearchKeywordManagement
        arguments:
            - '@doctrine'
            - ~
    lychee.module.content_management.content_blocking:
        class: Lychee\Module\ContentManagement\ContentBlockingService
        arguments:
            - '@doctrine'
    lychee.module.content_management.review_state:
        class: Lychee\Module\ContentManagement\ReviewStateService
        arguments:
            - '@doctrine'
    lychee.module.content_management.expression:
        class: Lychee\Module\ContentManagement\ExpressionManagement
        arguments:
            - '@doctrine'
            - ~
    lychee.module.content_management.android_auto_update:
        class: Lychee\Module\ContentManagement\AndroidAutoUpdateManager
        arguments:
            - '@doctrine'