services:
    lychee.module.game:
        class: Lychee\Module\Game\GameManager
        arguments: ['@doctrine']
    lychee.module.game_banner:
        class: Lychee\Module\Game\BannerManager
        arguments: ['@doctrine']
    lychee.task.calculate_game_banner_views:
        class: Lychee\Module\Game\Task\GameBannerViewsTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}
    lychee.module.game_category:
      class: Lychee\Module\Game\GameCategoryManager
      arguments: ['@doctrine']
    lychee.module.game_columns:
      class: Lychee\Module\Game\GameColumnsManager
      arguments: ['@doctrine']
    lychee.module.game_columns_recommendation:
      class: Lychee\Module\Game\GameColumnsRecommendationManager
      arguments: ['@doctrine']