services:
    lychee.module.recommendation:
        class: Lychee\Module\Recommendation\RecommendationService
        arguments: ['@doctrine', ~, '@memcache.default', '@snc_redis.recommendation', '@service_container']

    lychee.module.recommendation.banner:
        class: Lychee\Module\Recommendation\BannerService
        arguments:
            - '@doctrine'
            - ~

    lychee.module.recommendation.group_manager:
        class: Lychee\Module\Recommendation\Post\GroupManager
        arguments: ['@doctrine']

    lychee.module.recommendation.group_posts:
        class: Lychee\Module\Recommendation\Post\GroupPostsService
        arguments: ['@doctrine', '@lychee.module.recommendation.last_modified_manager', '@service_container']

    lychee.module.recommendation.group_posts_settle_processor:
        class: Lychee\Module\Recommendation\Post\SettleProcessor
        arguments: ['@doctrine', '@lychee.module.recommendation.group_manager']

    lychee.module.recommendation.last_modified_manager:
        class: Lychee\Module\Recommendation\LastModifiedManager
        arguments: ['@memcache.default']

    lychee.module.recommendation.event_subscriber:
        class: Lychee\Module\Recommendation\EventSubscriber
        arguments:
            - '@lychee.module.recommendation'
        tags:
            - {name: kernel.event_subscriber}


    lychee.task.settle_hots:
        class: Lychee\Module\Recommendation\Task\SettleHotsTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}


    lychee.task.settle_pass_audit_hots:
        class: Lychee\Module\Recommendation\Task\SettlPassAuditHotsTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}

    lychee.task.settle_user_ranking_post:
        class: Lychee\Module\Recommendation\Task\SettleUserRankingPostTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}
    lychee.module.special_subject:
        class: Lychee\Module\Recommendation\SpecialSubjectManagement
        arguments: ['@doctrine', ~]
    lychee.task.publish_recommendation:
        class: Lychee\Module\Recommendation\Task\PublishRecommendationTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}
    lychee.module.recommendation_column:
        class: Lychee\Module\Recommendation\ColumnManagement
        arguments: ['@doctrine', ~]
    lychee.module.recommendation.capture_site.bilibili:
        class: Lychee\Module\Recommendation\Task\BilibiliSite
    lychee.module.recommendation.capture_site.acfun:
        class: Lychee\Module\Recommendation\Task\AcfunSite

# 2017.03.01 停止视频网站的数据抓取
#    lychee.task.capture_site_content:
#            class: Lychee\Module\Recommendation\Task\CaptureSiteContentTask
#            calls:
#                - [setContainer, ['@service_container']]
#                - [attach, [['@lychee.module.recommendation.capture_site.bilibili', '@lychee.module.recommendation.capture_site.acfun']]]
#            tags:
#                - {name: lychee.task}

    lychee.module.app_channel:
        class: Lychee\Module\Recommendation\AppChannelManagement
        arguments: ['@doctrine', ~, '@lychee.component.storage']
    lychee.task.calculate_banner_views:
        class: Lychee\Module\Recommendation\Task\BannerViewsTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}

    lychee.consumer.recommendable_topic.create:
        class: Lychee\Component\EventDispatcher\DynamicAsyncConsumer
        arguments:
            - '@?monolog.logger.consumer'
            - '@lychee.module.recommendation'
            - 'asyncAfterCreateTopic'

    lychee.consumer.recommendable_topic.delete:
        class: Lychee\Component\EventDispatcher\DynamicAsyncConsumer
        arguments:
            - '@?monolog.logger.consumer'
            - '@lychee.module.recommendation'
            - 'asyncAfterDeleteTopic'