services:
    lychee.component.storage:
        class: Lychee\Component\Storage\QiniuStorage
        arguments:
            - %qiniu_access_key%
            - %qiniu_secret_key%
            - "%qiniu_upload_host%"
            - ciyocon
            - "upload/"
            - ciyocon-freeze
