services:
    lychee.module.ugsv.bgm:
        class: Lychee\Module\UGSV\BGMService
        arguments:
            - '@doctrine'
            - ~
    lychee.module.ugsv.whitelist:
        class: Lychee\Module\UGSV\WhiteListService
        arguments:
            - '@doctrine'
            - ~
    lychee.component.video:
        class: Lychee\Component\Video\TXVod
        arguments:
            - %tx_secret_id%
            - %tx_secret_key%
            - "%txvod_api_host%"
    lychee.task.settle_hot_videos:
        class: Lychee\Module\UGSV\Task\SettleHotVideosTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}
    lychee.task.settle_newly_videos:
        class: Lychee\Module\UGSV\Task\SettleNewLyVideosTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}
    lychee.task.settle_rec_videos:
        class: Lychee\Module\UGSV\Task\SettleRecVideosTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}

    lychee.module.ugsv.cover_store_event_subscriber:
        class: Lychee\Module\UGSV\CoverStoreEventSubscriber
        arguments:
            - '@service_container'
        tags:
            - {name: kernel.event_subscriber}

    lychee.task.move_video_cover_store:
        class: Lychee\Module\UGSV\Task\MoveCoverStoreTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}

    lychee.task.move_video_play_stat_store:
        class: Lychee\Module\UGSV\Task\MovePlayStatStoreTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}