lychee_admin:
    resource: "@LycheeAdminBundle/Controller"
    type:     annotation

lychee_admin_signout:
    path: /signout

lychee_admin_signin_check:
    path: /signin_check

_lychee_core:
    resource: "@LycheeCoreBundle/Resources/config/routing.yml"

_lychee_admin:
    resource: "@LycheeAdminBundle/Resources/config/routing.yml"