security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Lychee\Bundle\AdminBundle\Entity\Manager: sha256

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        managers:
            id: lychee_admin.service.manager

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/signin$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: lychee_admin_signin_check
                login_path: /signin
                default_target_path: /
                username_parameter: email
                password_parameter: password
            logout:
                path: lychee_admin_signout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
