services:
    lychee.module.activitytopciyobyweek.topciyobyweek:
        class: Lychee\Module\CiyoActivity\TopCiyoByWeekService
        arguments:
            - '@doctrine'
            - '@lychee.module.post'
            - '@lychee.module.account'

