services:
    lychee.module.content_audit:
        class: Lychee\Module\ContentAudit\ContentAuditService
        arguments:
            - '@doctrine'
            - ~
    lychee.module.image_review:
        class: Lychee\Module\ContentAudit\ImageReviewService
        arguments:
            - '@doctrine'
            - '@monolog.logger.image_review'
            - '@kernel'
            - "%tupu_secret_id%"
            - "%kernel.environment%"
            - '@lychee.component.storage'
            - '@lychee.module.post'
    lychee.module.content_audit.event_subscriber:
        class: Lychee\Module\ContentAudit\EventSubscriber
        arguments:
            - '@lychee.module.post'
            - '@lychee.module.image_review'
            - "%kernel.environment%"
            - '@lychee.component.storage'
            - '@lychee.module.account'
            - '@lychee.module.topic'
            - "%kernel.cache_dir%"
        tags:
            - {name: kernel.event_subscriber}
    lychee.module.content_audit.anni_rubbish_event_subscriber:
        class: Lychee\Module\ContentAudit\AntiRubbishEventSubscriber
        arguments:
            - '@doctrine'
            - '@lychee.module.post'
            - '@lychee.module.comment'
        tags:
            - {name: kernel.event_subscriber}
    lychee.task.clear_review_source:
        class: Lychee\Module\ContentAudit\Task\ClearReviewSource
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}