services:
    lychee.module.extramessage:
        class: Lychee\Module\ExtraMessage\ExtraMessageService
        arguments:
            - '@doctrine'
            - '@memcache.default'

    lychee.module.emuser:
        class: Lychee\Module\ExtraMessage\EMUserService
        arguments:
            - '@doctrine'
            - '@memcache.default'

    lychee.module.empicturerecord:
        class: Lychee\Module\ExtraMessage\EMPictureRecordService
        arguments:
            - '@doctrine'
            - '@memcache.default'

    lychee.module.emauthentication:
            class: Lychee\Module\ExtraMessage\EMAuthenticationService
            arguments:
                - '@doctrine'
                - '@lychee.module.authentication.encoder'
                - %yiciyuan_sinaweibo_client_key%
                - %yiciyuan_qq_app_key%
                - '@logger'
                - '@lychee.module.authentication.token_issuer'


    lychee.module.caituservice:
            class: Lychee\Module\Caitu\CaituService
            arguments:
                - '@doctrine'


    lychee.task.extramessage.payment_ranking_all:
                class: Lychee\Module\ExtraMessage\Task\EMPaymentRankingAllTask
                calls:
                    - [setContainer, ['@service_container']]
                tags:
                    - {name: lychee.task}

    lychee.task.extramessage.payment_ranking_story:
                class: Lychee\Module\ExtraMessage\Task\EMPaymentRankingStoryTask
                calls:
                    - [setContainer, ['@service_container']]
                tags:
                    - {name: lychee.task}

    lychee.task.extramessage.payment_ranking_story_recent:
                class: Lychee\Module\ExtraMessage\Task\EMPaymentRankingRecentTask
                calls:
                    - [setContainer, ['@service_container']]
                tags:
                    - {name: lychee.task}