services:
    lychee.module.robot:
        class: Lychee\Module\Robot\RobotService
        arguments:
            - '@doctrine'
            - '@service_container'

    lychee.component.counter.robot:
        class: Lychee\Component\Counter\RedisCounter
        arguments:
            - '@snc_redis.robot'
