lychee_image_upload:
    path: '/upload/{hash}/{filter}'
#    host: %lychee.module.upload.image_domain%
    methods: [GET]
    defaults: {_controller: lychee.module.upload:requestImage, filter: ~}

lychee_image_upload2:
    path: '/upload/{hash}/{filter}/{filterParam}'
    #    host: %lychee.module.upload.image_domain%
    methods: [GET]
    defaults: {_controller: lychee.module.upload:requestImage, filter: ~, filterParam: ~}