services:
    lychee.module.schedule:
        class: Lychee\Module\Schedule\ScheduleService
        arguments:
            - '@doctrine'
            - '@lychee.event_dispatcher_async'

    lychee.module.schedule.start_notification_task:
        class: Lychee\Module\Schedule\Task\StartNotificationTask
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: lychee.task}

    lychee.module.schedule.event_subscriber:
        class: Lychee\Module\Schedule\EventSubscriber
        arguments:
            - '@lychee.module.schedule'
            - '@lychee.module.notification'
        tags:
            - {name: kernel.event_subscriber}
