services:
    lychee.module.search.accountIndexer:
        class: Lychee\Module\Search\UserIndexer
        arguments: ['@fos_elastica.index.ciyo.user']

    lychee.module.search.accountSearcher:
        class: Lychee\Module\Search\AbstractSearcher
        arguments: ['@fos_elastica.index.ciyo.user']

    lychee.module.search.accountProvider:
        class: Lychee\Module\Search\UserProvider
        arguments:
            - '@lychee.module.search.accountIndexer'
            - '@doctrine'
        tags:
            - {name: fos_elastica.provider, index: ciyo, type: user}

    lychee.module.search.topicIndexer:
        class: Lychee\Module\Search\TopicIndexer
        arguments: ['@fos_elastica.index.ciyo.topic']

    lychee.module.search.topicSearcher:
        class: Lychee\Module\Search\TopicSearcher
        arguments: ['@fos_elastica.index.ciyo.topic']

    lychee.module.search.topicProvider:
        class: Lychee\Module\Search\TopicProvider
        arguments:
            - '@lychee.module.search.topicIndexer'
            - '@doctrine'
        tags:
            - {name: fos_elastica.provider, index: ciyo, type: topic}

    lychee.module.search.superiorTopicIndexer:
        class: Lychee\Module\Search\TopicIndexer
        arguments: ['@fos_elastica.index.ciyo.superior_topic']

    lychee.module.search.superiorTopicSearcher:
        class: Lychee\Module\Search\TopicSearcher
        arguments: ['@fos_elastica.index.ciyo.superior_topic']

    lychee.module.search.superiorTopicProvider:
        class: Lychee\Module\Search\SuperiorTopicProvider
        arguments:
            - '@lychee.module.search.superiorTopicIndexer'
            - '@doctrine'
        tags:
            - {name: fos_elastica.provider, index: ciyo, type: superior_topic}

    lychee.module.search.postIndexer:
        class: Lychee\Module\Search\PostIndexer
        arguments: ['@fos_elastica.index.ciyo.post', '@lychee.module.topic']

    lychee.module.search.postSearcher:
        class: Lychee\Module\Search\PostSearcher
        arguments: ['@fos_elastica.index.ciyo.post']

    lychee.module.search.resourcePostSearcher:
        class: Lychee\Module\Search\ResourcePostSearcher
        arguments: ['@fos_elastica.index.ciyo.post']

    lychee.module.search.topicPostSearcher:
        class: Lychee\Module\Search\TopicPostSearcher
        arguments: ['@fos_elastica.index.ciyo.post']

    lychee.module.search.postProvider:
        class: Lychee\Module\Search\PostProvider
        arguments:
            - '@lychee.module.search.postIndexer'
            - '@doctrine'
        tags:
            - {name: fos_elastica.provider, index: ciyo, type: post}

    lychee.module.search.superiorPostIndexer:
        class: Lychee\Module\Search\PostIndexer
        arguments: ['@fos_elastica.index.ciyo.superior_post', '@lychee.module.topic']

    lychee.module.search.superiorPostSearcher:
        class: Lychee\Module\Search\PostSearcher
        arguments: ['@fos_elastica.index.ciyo.superior_post']

    lychee.module.search.superiorResourcePostSearcher:
        class: Lychee\Module\Search\ResourcePostSearcher
        arguments: ['@fos_elastica.index.ciyo.superior_post']

    lychee.module.search.superiorTopicPostSearcher:
        class: Lychee\Module\Search\TopicPostSearcher
        arguments: ['@fos_elastica.index.ciyo.superior_post']

    lychee.module.search.superiorPostProvider:
        class: Lychee\Module\Search\SuperiorPostProvider
        arguments:
            - '@lychee.module.search.superiorPostIndexer'
            - '@doctrine'
        tags:
            - {name: fos_elastica.provider, index: ciyo, type: superior_post}

    lychee.module.search.topicFollowerIndexer:
        class: Lychee\Module\Search\TopicFollowerIndexer
        arguments: ['@fos_elastica.index.ciyo.topic_follower', '@lychee.module.account']

    lychee.module.search.topicFollowerSearcher:
        class: Lychee\Module\Search\TopicFollowerSearcher
        arguments: ['@fos_elastica.index.ciyo.topic_follower']

    lychee.module.search.topicFollowerProdiver:
        class: Lychee\Module\Search\TopicFollowerProvider
        arguments:
            - '@lychee.module.search.topicFollowerIndexer'
            - '@doctrine'
        tags:
            - {name: fos_elastica.provider, index: ciyo, type: topic_follower}

    lychee.module.search.event_subscriber:
        class: Lychee\Module\Search\EventSubscriber
        arguments:
            - '@lychee.module.search.accountIndexer'
            - '@lychee.module.account'
            - '@lychee.module.search.topicIndexer'
            - '@lychee.module.topic'
            - '@lychee.module.search.postIndexer'
            - '@lychee.module.post'
            - '@lychee.module.search.topicFollowerIndexer'
            - '@lychee.module.topic.following'
        tags:
            - {name: kernel.event_subscriber}