parameters:


services:
#    lychee_admin.example:
#        class: %lychee_admin.example.class%
#        arguments: ['@service_id', "plain_value", %parameter%]
    lychee.event_dispatcher:
        class: Lychee\Component\EventDispatcher\SuppressExceptionEventDispatcher
        arguments: ['@event_dispatcher', '@?logger']

    lychee.event_dispatcher_async:
        class: Lychee\Component\EventDispatcher\AsyncEventDispatcher
        arguments: ['@old_sound_rabbit_mq.event_producer', '@?logger']

    lychee.dynamic_dispatcher_async:
        class: Lychee\Component\EventDispatcher\DynamicAsyncDispatcher
        arguments: ['@service_container', '@?logger']

    lychee.event_consumer:
        class: Lychee\Component\EventDispatcher\AsyncEventConsumer
        arguments:
            - '@event_dispatcher'
            - '@?monolog.logger.consumer'
            - '@doctrine'
            - '@lychee.module.notification.push'

    lychee.task.manager:
        class: Lychee\Component\Task\TaskManager
        arguments: ['@doctrine', '@monolog.logger.task']

    lychee.twig_extension:
        class: Lychee\Bundle\CoreBundle\Twig\Extension
        public: false
        tags:
            - { name: twig.extension }

imports:
    - { resource: account.yml }
    - { resource: activity.yml }
    - { resource: authentication.yml }
    - { resource: comment.yml }
    - { resource: content_management.yml }
    - { resource: like.yml }
    - { resource: measurement.yml }
    - { resource: notification.yml }
    - { resource: post.yml }
    - { resource: promotion.yml }
    - { resource: recommendation.yml }
    - { resource: relation.yml }
    - { resource: report.yml }
    - { resource: topic.yml }
    - { resource: analysis.yml }
    - { resource: search.yml }
    - { resource: storage.yml }
    - { resource: im.yml }
    - { resource: schedule.yml }
    - { resource: voting.yml }
    - { resource: content_audit.yml }
    - { resource: operation.yml }
    - { resource: game.yml }
    - { resource: promotion.yml }
    - { resource: payment.yml }
    - { resource: favorite.yml }
    - { resource: live.yml }
    - { resource: extramessage.yml }
    - { resource: ugsv.yml }
    - { resource: activity_top_ciyo_by_week.yml }
    - { resource: robot.yml }
