parameters:

services:
    lychee_api.synthesizer_builder:
        class: Lychee\Bundle\ApiBundle\DataSynthesizer\SynthesizerBuilder
        calls: [[setContainer, ['@service_container']]]

    lychee_api.spam_checker:
        class: Lychee\Bundle\ApiBundle\AntiSpam\SpamChecker
        arguments: ['@snc_redis.spam']

    lychee_api.spammer_recorder:
        class: Lychee\Bundle\ApiBundle\AntiSpam\SpammerRecorder
        arguments: ['@doctrine']

    lychee_api.ip_blocker:
        class: Lychee\Bundle\ApiBundle\IpBlocker\IpBlocker
        arguments: ['@doctrine']

    lychee_api.sms_recorder:
        class: Lychee\Bundle\ApiBundle\SmsRecoder\SmsRecorder
        arguments: ['@doctrine','@service_container']