imports:
    - { resource: "bundles/doctrine.yml" }
    - { resource: "bundles/doctrine-dbals.yml" }
    - { resource: "bundles/lsw_memcache.yml" }
    - { resource: "bundles/old_sound_rabbit_mq.yml" }
    - { resource: "bundles/snc_redis.yml" }
    - { resource: "bundles/fos_elastica.yml" }

#Dependency Injection
#jms_di_extra:
#    locations:
#        all_bundles: false
#        bundles: [LycheeApiBundle, LycheeCoreBundle]
#        directories: ["../../src"]

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Monolog Configuration
monolog:
    channels: [task, command, sms, consumer, image_review, thirdparty_invoke]
    handlers:
        task:
            type: stream
            level: debug
            path: "%kernel.root_dir%/../../var/task/task.log"
            channels: [task]
        command:
            type: stream
            level: error
            path: "%kernel.root_dir%/../../var/command/error.log"
            channels: [command]
        sms:
            type: stream
            level: debug
            path: "%kernel.root_dir%/../../var/sms.log"
            channels: [sms]
        consumer:
            type: stream
            level: debug
            path: "%kernel.root_dir%/../../var/consumer.log"
            channels: [consumer]
        image_review:
            type: rotating_file
            level: info
            path: "%kernel.root_dir%/../../var/image_review.log"
            channels: [image_review]
            max_files: 10
        thirdparty_invoke:
            type: rotating_file
            level: info
            path: "%kernel.root_dir%/../../var/thirdparty_invoke.log"
            channels: [thirdparty_invoke]
            max_files: 3

#bazinga_geocoder:
#    adapter:
#        class: ~
#    providers:
#        ~

lychee_core:
    image_domain: %image_server_domain%
    image_upload_path: %kernel.root_dir%/../../upload
    sensitive_words: %kernel.root_dir%/../config/sensitive_words